export const units = {
  cup: ['c', 'c.', 'C', 'Cups'],
  gallon: ['gal'],
  ounce: ['oz', 'oz.'],
  pint: ['pt', 'pts', 'pt.'],
  pound: ['lb', 'lb.', 'lbs', 'lbs.', 'Lb', 'Lbs'],
  quart: ['qt', 'qt.', 'qts', 'qts.'],
  tablespoon: ['tbs', 'tbsp', 'tbspn', 'tbspns', 'T', 'T.', 'Tablespoons', 'Tablespoon'],
  teaspoon: ['tsp', 'tspn', 'tspns', 't', 't.', 'Teaspoons', 'Teaspoon'],
  gram: ['g', 'g.', 'grammes', 'grams'],
  kilogram: ['kg', 'kg.', 'Kg', 'Kg.', 'kilo', 'kilos', 'kilogrammes', 'kilograms', 'kilogram'],
  liter: ['l', 'l.', 'L', 'L.'],
  milligram: ['mg', 'mg.'],
  milliliter: ['ml', 'ml.', 'mL', 'mL.'],
  package: ['pkg', 'pkgs'],
  stick: ['sticks'],
  piece: ['pcs', 'pcs.'],
  pinch: ['pinch'],
  small: ['Small'],
  medium: ['Medium'],
  large: ['large', 'Large'],
  sprinkle: ['sprinkle'],
  dash: ['dash'],
  clove: ['cloves'],
  can: ['cans'],
  slice: ['slices'],
  bag: ['bags'],
  box: ['boxes'],
  bunch: ['bunches'],
  head: ['heads'],
  jar: ['jars'],
  loaf: ['loaves'],
  sprig: ['sprigs'],
} as { [key: string]: string[] };

export const pluralUnits = {
  cup: 'cups',
  gallon: 'gallons',
  ounce: 'ounces',
  pint: 'pints',
  pound: 'pounds',
  quart: 'quarts',
  tablespoon: 'tablespoons',
  teaspoon: 'teaspoons',
  gram: 'grams',
  kilogram: 'kilograms',
  liter: 'liters',
  milligram: 'milligrams',
  milliliter: 'milliliters',
  clove: 'cloves',
  bag: 'bags',
  box: 'boxes',
  pinch: 'pinches',
  can: 'cans',
  slice: 'slices',
  piece: 'pieces'
} as { [key: string]: string };
